[
  {
    "Emp_Id": "1111",
    "First_Name": "Daniel",
    "Last Name": "White",
    "Date of Birth": "10-11-1965",
    "Joining Date": "01-01-2001",
    "Termination Date": "",
    "Employee Status": "Employeed",
    "Payment Status": "",
    "Phone Number": "9898787866",
    "Address": "Flat No 001, Fake Street, Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1112",
    "First_Name": "Austin",
    "Last Name": "James",
    "Date of Birth": "15-08-1967",
    "Joining Date": "15-01-2001",
    "Termination Date": "",
    "Employee Status": "Employeed",
    "Payment Status": "",
    "Phone Number": "9898787896",
    "Address": "Flat No 002, Fake Street, Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1113",
    "First_Name": "Peter",
    "Last Name": "Carolina",
    "Date of Birth": "19-05-1969",
    "Joining Date": "29-01-2001",
    "Termination Date": "",
    "Employee Status": "Employeed",
    "Payment Status": "",
    "Phone Number": "9898787926",
    "Address": "Flat No 001, Fake Street, Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1114",
    "First_Name": "Glenn",
    "Last Name": "Bison",
    "Date of Birth": "21-02-1971",
    "Joining Date": "12-02-2001",
    "Termination Date": "",
    "Employee Status": "Employeed",
    "Payment Status": "",
    "Phone Number": "9898787956",
    "Address": "Flat No 002, Fake Street, Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1115",
    "First_Name": "Mark",
    "Last Name": "Henry",
    "Date of Birth": "25-11-1972",
    "Joining Date": "26-02-2001",
    "Termination Date": "",
    "Employee Status": "Employeed",
    "Payment Status": "",
    "Phone Number": "9898787986",
    "Address": "Flat No 001, Fake Street, Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1116",
    "First_Name": "Sadio",
    "Last Name": "Mane",
    "Date of Birth": "02-10-1998",
    "Joining Date": "27-02-2001",
    "Termination Date": "",
    "Employee Status": "Employeed",
    "Payment Status": "",
    "Phone Number": "9898787987",
    "Address": "Flat No 001, Fake Street, Pune",
    "Status": ""
  },
  {
    "Emp_Id": "1117",
    "First_Name": "Ronaldinho",
    "Last Name": "Gacha",
    "Date of Birth": "25-11-1962",
    "Joining Date": "28-02-2001",
    "Termination Date": "",
    "Employee Status": "Employeed",
    "Payment Status": "",
    "Phone Number": "9898787988",
    "Address": "Flat No 001, Fake Street, Pune",
    "Status": ""
  }
]